#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

sxhkd -c $HOME/.config/sxhkd/sxhkdrc &

# LOAD HERE THE EWW WIDGETS
picom --daemon --config $SCRIPTPATH/picom.conf

feh --bg-scale $SCRIPTPATH/wallpaper.jpeg

eww daemon &
sleep 1

eww open statusbar

# screens=$(xrandr --listmonitors | grep "Monitors" | awk '{print $2}')
# connected_screens=$(xrandr --listmonitors | awk '{print $4}')

# # check if there are more than one screen
# if [ $screens -gt 1 ]; then
#     # check if the second screen is connected
#     # if [ $connected_screens == "yes" ]; then
#     eww open statusbarSecondary --screen DP-1
#     # fi
# fi
